### ISSUE TITLE
DateInterval not working

### ISSUE THREAD

**Issue by starkadur** [spraakbanken/korp-backend#16]
I have added -date_interval as a structural attribute for one of my corpora:

  \- date_interval:
      label:
        eng: Time interval
        is: Tímabil
      hide_sidebar: 'true'
      hide_compare: 'true'
      hide_statistics: 'true'
      opts: false
      extended_component: dateInterval

When I search for the word "kona" and the time interval from 2018-01-01 to 2019-01-01 I get no results. When I look at the active cqp-query in advanced search it is like this:

  `[lemma = "kona" & _.date_interval = "20180101,20230104,000000,235959"]`

If I do similar search on the Swedish Korp the active cqp-query looks like this:

`[word = "och" & ((int(_.text_datefrom) = 20180101 & int(_.text_timefrom) >= 094500) | (int(_.text_datefrom) > 20180101 & int(_.text_datefrom) <= 20191231)) & (int(_.text_dateto) < 20191231 | (int(_.text_dateto) = 20191231 & int(_.text_timeto) <= 235959))]`

... and if I change the word from "och" to "kona" and insert this into "Fullständig CQP-fråga" in my version of Korp it works and I get some results.

So how come I don't get the same extended cqp-query when using the datepicker that dateInterval creates, and why does the query I get not work?

**Comment by majsan** [comment]
The issue might be that the CQP is not transformed correctly in `cqp.js`. You can probably use printouts our a debugger to see if `parseDateInterval` is doing what it is supposed to.

Did you add this to config.yml in the frontend or as an attribute in the backend? I don't know why that would break it, but it could be the issue. If you don't know what I mean, in Språkbankens setup, this is added to the frontends `config.yml`:

```
common_struct_types:
  date_interval:
    label: 
      eng: time interval
      swe: tidsintervall
    hide_sidebar: 'true'
    hide_compare: 'true'
    hide_statistics: 'true'
    opts: false
    extended_component: dateInterval
``` 

See (https://github.com/spraakbanken/korp-frontend-sb/blob/dev/app/config.yml)
